### ISSUE TITLE
Expose indexDocumentsMethod in Index.add_documents to update documents

### ISSUE THREAD

**Issue by mjordan** [AlexAltea/milli-py#3]
Will there be an `update_documents` method or will replacing with `add_documents` be the preferred way?

**Comment by AlexAltea** [comment]
I've tried to make the API resemble the original as much as possible (as much as Rust lifetimes allow).

Milli only exposes `add_documents`, where the default behavior is replacing existing documents with identical IDs with a newer version, see https://github.com/meilisearch/milli/blob/758b4acea7cecd689650bee65949b49cf09ddaa3/milli/src/update/index_documents/mod.rs#L69

Because of this, right now, you can "replace" but not "update" documents.

In a future version, I'll expose these optional keyword arguments via:
```py
Index.add_documents(..., update_strategy=IndexDocumentsMethod.ReplaceDocuments)
```

**Comment by AlexAltea** [comment]
This is now possible as of https://github.com/AlexAltea/milli-py/commit/7e0fb580267748270aa60324552fb689506bfd9b.

Example: https://github.com/AlexAltea/milli-py/blob/7e0fb580267748270aa60324552fb689506bfd9b/tests/test_milli_index.py#L18-L38

**Comment by itsthejoker** [comment]
@AlexAltea can you create a new release for PyPI? This change is not present in the current release. Thanks!
